library(reticulate)
library(tibble)
np <- import("numpy")
xyz <- np$load("/Users/roaldarbol/Downloads/sesh_21-07-20_165209_noOpenPose/DataArrays/openPoseSkel_3d.npy")
x <- as_tibble(xyz[,,1])
y <- as_tibble(xyz[,,2])
z <- as_tibble(xyz[,,3])
